### PR TITLE
Fixes 53#issue-782891651 java.lang.ArrayIndexOutOfBoundsException 

### PR DESCRIPTION
**Pull request by gregoreficint**
Please see issue https://github.com/opentimestamps/java-opentimestamps/issues/53#issue-782891651

### CODE REVIEW

**Comment by RCasatta** [comment]
The PR looks good, however, it looks causing an error in another test.
I will investigate more...

```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.eternitywall.ots.attestation.TestUnknownAttestation                                                                                                                       
[ERROR] deserializationTooLong(com.eternitywall.ots.attestation.TestUnknownAttestation)  Time elapsed: 0.001 s  <<< ERROR!                                                                                                                                                      
java.lang.NullPointerException                                                                                                                                                                                                                                                  
        at com.eternitywall.ots.attestation.TestUnknownAttestation.deserializationTooLong(TestUnknownAttestation.java:64)      
```

**Comment by gregoreficint** [comment]
Than you for the fast review. I looked a little bit deeper and I believe that the test does not test at all what it is designed to do, even if I don't know the underlying protocol. Let's dig into it:
The original test looks like this:
```
public void deserializationTooLong() throws IOException {
    // Deserialization of attestations with oversized payloads
    ByteArrayOutputStream baos1 = new ByteArrayOutputStream();
    baos1.write(hexToBytes("0102030405060708"));
    baos1.write(0x81);
    baos1.write(0x40);
    baos1.write('x' * 8193);
    StreamDeserializationContext ctx = new StreamDeserializationContext(baos1.toByteArray());
    UnknownAttestation a = (UnknownAttestation) TimeAttestation.deserialize(ctx);
    // TODO: exception

    // Pending attestation
    ByteArrayOutputStream baos2 = new ByteArrayOutputStream();
    baos2.write(hexToBytes("83dfe30d2ef90c8e"));
    baos2.write(0x81);
    baos2.write(0x40);
    baos2.write('x' * 8193);
    StreamDeserializationContext ctx1 = new StreamDeserializationContext(baos2.toByteArray());
    UnknownAttestation a1 = (UnknownAttestation) TimeAttestation.deserialize(ctx1);
    // TODO: exception
}
```

If we look at the routine that is supposed to be tested we see
```
public static TimeAttestation deserialize(StreamDeserializationContext ctx) {
    // console.log('attestation deserialize');

    byte[] tag = ctx.readBytes(_TAG_SIZE);
    // console.log('tag: ', com.eternitywall.ots.Utils.bytesToHex(tag));

    byte[] serializedAttestation = ctx.readVarbytes(_MAX_PAYLOAD_SIZE);
    // console.log('serializedAttestation: ', com.eternitywall.ots.Utils.bytesToHex(serializedAttestation));

    StreamDeserializationContext ctxPayload = new StreamDeserializationContext(serializedAttestation);

    /* eslint no-use-before-define: ["error", { "classes": false }] */
    if (Arrays.equals(tag, PendingAttestation._TAG) == true) {
        return PendingAttestation.deserialize(ctxPayload);
    } else if (Arrays.equals(tag, BitcoinBlockHeaderAttestation._TAG) == true) {
        return BitcoinBlockHeaderAttestation.deserialize(ctxPayload);
    } else if (Arrays.equals(tag, LitecoinBlockHeaderAttestation._TAG) == true) {
        return LitecoinBlockHeaderAttestation.deserialize(ctxPayload);
    } else if (Arrays.equals(tag, EthereumBlockHeaderAttestation._TAG) == true) {
        return EthereumBlockHeaderAttestation.deserialize(ctxPayload);
    }

    return new UnknownAttestation(tag, serializedAttestation);
}
```
with _TAG_SIZE=8 and _MAX_PAYLOAD_SIZE=8192.

So the first thing we notice in the test routine is that twice the payload is constructed by write('x' * 8193). I assume the author wanted to create 8193 bytes to break the MAX_PAYLOAD_SIZE. Unfortunately, the expression 'write('x' * 8193)' does not create 8193 bytes but the compiler multiples 120(='x')* 8193 which leads to the number 983160. This number is then truncated to one byte only (120) and one byte rather than 8193 bytes are written. However, the length of the payload is still specified by `baos2.write(0x81);baos2.write(0x40);` to be 8193 bytes. This leads in the second part of the test case to the exception.

However, this is not the only part of the method that is wrong. In the second part of the test the case of "pending attestation" is to be tested. However, if the method under tests works correctly, the result must be of is type PendingAttestation rather than UnknownAttestation as written in the test case. 

The only reason the tests passes is because the StreamDeserializationContext.read() method was broken in the first place. If we correct the test file with three changes to be
```
@Test
public void deserializationTooLong() throws IOException {
    // Deserialization of attestations with oversized payloads
    ByteArrayOutputStream baos1 = new ByteArrayOutputStream();
    baos1.write(hexToBytes("0102030405060708"));
    baos1.write(0x81);
    baos1.write(0x40);
    for(int i=0;i<8193;i++)
        baos1.write('x');
    StreamDeserializationContext ctx = new StreamDeserializationContext(baos1.toByteArray());
    UnknownAttestation a = (UnknownAttestation) TimeAttestation.deserialize(ctx);
    // TODO: exception

    // Pending attestation
    ByteArrayOutputStream baos2 = new ByteArrayOutputStream();
    baos2.write(hexToBytes("83dfe30d2ef90c8e"));
    baos2.write(0x81);
    baos2.write(0x40);
    for(int i=0;i<8193;i++)
        baos2.write('x');
    StreamDeserializationContext ctx1 = new StreamDeserializationContext(baos2.toByteArray());
    PendingAttestation a1 = (PendingAttestation) TimeAttestation.deserialize(ctx1);
    // TODO: exception
}
```
it passes with the correct new implementation of read.

However, I am really not sure whether the behaviour of the method deserialization and its test should be as it is. Right now, it is acceptable that the payload is larger than the limit. Wouldn't you want to throw some exception in the deserialization if the payload is higher than the limit allowed? The way it is currently handled is that no exception or warning is given and the higher length of payload is accepted silently. Is this really the desired behaviour?

**Comment by gregoreficint** [comment]
@RCasatta I would like to conclude the matter. Could you, please, either confirm to me that you would like to keep the current behaviour of TimeAttestation.deserialize (to not throw an exception if payload is higher than the limit) or to throw an exception? I cannot answer that question because I am not familiar with the protocol used. After your answer, I would make a pull request with the changed test and/or changed behaviour of the function .deserialize. Thanks!

**Comment by RCasatta** [comment]
If the payload is higher than the limit an exception should be thrown.

When in doubt follow the reference implementation (the python one) https://github.com/opentimestamps/python-opentimestamps/blob/5ac3b0642b29e2092c75d164561d37842cd50d29/opentimestamps/core/serialize.py#L210

And yes the test `deserializationTooLong` is broken as you noticed (probably the result of porting from python/javascript)

**Comment by gregoreficint** [comment]
I introduced some exception handling that resulted in many files being changed. It tests successfully on my machine and I believe it strengthens the overall dealing with exceptions. Please let me know, what you think.

**Comment by RCasatta** [comment]
Looking good, going to merge, thanks.

**Pull request merged**
