### PR TITLE
Automatic formatting optimize import whitespace

### PR DESCRIPTION
**Pull request by matshenricson**
This is JUST automatic formatting and import optimizations by IntelliJ.
Plus that I manually added and removed some empty lines.

### CODE REVIEW

**Comment by lvaccaro** [comment]
ack for b9c7bc097b9cc05b5b0a99abaea5b9deb56bf4de

**Comment by RCasatta** [comment]
So, @lvaccaro and I discussed about the repo, we are better git user now than when this project was started. We would like to avoid having merge commit from now on. So for this PR we have 2 options:

- I can cherry pick just your b9c7bc097b9cc05b5b0a99abaea5b9deb56bf4de commit into master, you will remain the commit author but if you had any signature on it it would have been lost
- You can rebase your branch removing the merge commit (if you are not familiar we can help)

**Comment by matshenricson** [comment]
Pick any way you choose, I don't understand how I ended up in this git situation anyway.

**Comment by RCasatta** [comment]
this time I cherry picked c2bb4a033c2088b5877f62863efb5f5f97676bf4.

to avoid merge commit, you just need to rebase your branch. For example:

You create a new branch from latest master.
`git checkout -b new-branch`
you do some commits
when you create a PR someone else pushed stuff on master.
so you rebase your branch, it means your commits are re-applyed from the new latest master
for example:
`git fetch` #download the latest master
`git rebase origin/master`

**Comment by RCasatta** [comment]
Closing cause already cherry picked relevant commit

**Pull request closed without merging**
